### ISSUE TITLE
iOS 16 - Naming Issue

### ISSUE THREAD

**Issue by Tom2Drake** [thoukydides/homebridge-homeconnect#108]
Hi,

there is a issue with the Naming of the accessories since iOS 16. There are all the same now, what keeps me from using it.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/13260476/194751272-3b697e88-2157-473a-aee8-0908942c36e5.png">

Best regards
Frederick

**Comment by thoukydides** [comment]
This is an iOS 16 issue that cannot be fixed by this plugin. Please see https://github.com/thoukydides/homebridge-homeconnect/discussions/102 and https://github.com/homebridge/homebridge/issues/3210.

**Comment by thoukydides** [comment]
Based on a [Discord](https://discord.com/channels/432663330281226270/432672072859385856/1040394094528188416) discussion I have made some changes in v0.27.0 that help. (See #116 for more details.)
