### ISSUE TITLE
Has the Plugin an effect on the whole HomeConnect connection?

### ISSUE THREAD

**Issue by DJay-X** [thoukydides/homebridge-homeconnect#11]
@thoukydides Hope you are well.

I noticed with some of the latest updates of the plugin, that is not that reliable with my coffee maker than it was in older versions.

I notice just from time to time that when turning the machine on/off by Siri, the answer is that the device is not available.

Home Connect connection was available, checking the display on the device as well in the Home Connect App. However, short after giving this command to HomeKit the connection switched to "not available". Waiting a few minutes and the connection was back again.

![Napkin 25 01 20, 3 16 58 PM](https://user-images.githubusercontent.com/3874239/73122477-bfd79b80-3f85-11ea-9d76-05b9517e3e63.png)

Not sure if this is somehow in context. Or there is a mayor chance in something from 0.14.0 to the latest?

I will have an eye on that because at the moment I can't reproduce the error. Sometimes everting is working reliable and quick. The next time nothing works. 

I just want to keep you informed about my observation and give again feedback after some day.
Or maybe you have an Idea in advance.

Thanks again.

```
Jan 25 15:13:01 raspberrypi-3BPlus homebridge[439]: [2020-1-25 15:13:01] [HomeConnect] [Kaffeevollautomat] SET Off
Jan 25 15:13:11 raspberrypi-3BPlus homebridge[439]: [2020-1-25 15:13:11] [HomeConnect] [Kaffeevollautomat] Home Connect API error: Timeout on Home Connect subsystem. Please try it again. [SDK.Error.504.GatewayTimeout]
Jan 25 15:13:11 raspberrypi-3BPlus homebridge[439]: [2020-1-25 15:13:11] [HomeConnect] [Kaffeevollautomat] SET BSH.Common.Setting.PowerState=BSH.Common.EnumType.PowerState.Standby
Jan 25 15:13:11 raspberrypi-3BPlus homebridge[439]: [2020-1-25 15:13:11] [HomeConnect] [Kaffeevollautomat] PUT https://api.home-connect.com/api/homeappliances/BOSCH-CTL636ES6-12A34B5678C9/settings/BSH.Common.Setting.PowerState
```

**Comment by thoukydides** [comment]
If you look at the [Error Messages](https://github.com/thoukydides/homebridge-homeconnect/wiki/Errors#home-connect-api-unavailable) page on this project's Wiki you will see that these are problems with the Home Connect servers. There is nothing that I or this plugin can do about it.

I have been seeing exactly the same thing since last weekend, and have contacted [Home Connect developer support](https://developer.home-connect.com/support/contact) but not received any reply.

**Comment by DJay-X** [comment]
Sorry. Was not aware of this. 😌🙏 Didn't want to bother. Thanks.
