### ISSUE TITLE
Plugin does not connect

### ISSUE THREAD

**Issue by solbadguy2010** [thoukydides/homebridge-homeconnect#117]
#### Description of Issue
moved Plugin to a new pi with HB backup. Plugin does not reconnect.

#### Plugin Version
newest

#### Home Connect Appliance(s)
cooking plate and fridge

#### HomeKit App(s)
 Home

#### Diagnostic Checks
We deleted and re-created the dec-account and the oath flow app. no change. We are sure the client ID is correct. Any idea?

#### Log File
[23/12/2022, 12:27:30] [HomeConnect] Home Connect API error: Unable to authorise Home Connect application; request rejected by client authorization authority (developer portal). Visit https://developer.home-connect.com/applications to register an application and then copy its Client ID.

**Comment by thoukydides** [comment]
As the error message you quote says, that error is from the Home Connect servers, not this plugin.

If you check the [Home Connect API documentation](https://api-docs.home-connect.com/authorization?#authorization-errors) you will see that error described as:

Error Cause | Code | Error | Error Description | Redirection | JSON
-- | -- | -- | -- | -- | --
Invalid client ID or redirect URI | 400 | unauthorized_client | request rejected by client authorization authority (developer portal) |   | :heavy_check_mark:

Make sure your application is configured like this:

![client1](https://user-images.githubusercontent.com/4775242/209338407-ec1b70c5-56d5-435f-9f82-d965c97f9a4c.png)

![client2](https://user-images.githubusercontent.com/4775242/209338413-b79e6e5a-b398-4f11-98ee-d5d42313cd00.png)

Most likely you have either not correctly copied the Client ID into the plugin configuration, or you have not set a valid Success Redirect URL in the application configuration.

If you cannot get this to work then contact the Home Connect developer support at https://developer.home-connect.com/support/contact
