### ISSUE TITLE
Authorisation problem

### ISSUE THREAD

**Issue by jackscorpse** [thoukydides/homebridge-homeconnect#118]
#### Description of Issue
I can not pass authorization after SingleKey. I follow the link from the plugin with the authorization code on the Homeconnect site, after entering the email, I am redirected to the SingleKey, but after log in the SingleKey, a message appears that the device authorization session has expired.
About a month ago everything was working fine, I had configured the plugin several times before. But now something has changed in the Homeconnect services and I can't log in. I registered a new account in Homeconnect and added a device there, but when setting up the plugin in homebridge, the same error appeared.

#### Plugin Version
v0.27.0

#### Home Connect Appliance(s)
Bosch Dishwasher SPV2HMX4FR/02

**Comment by thoukydides** [comment]
That sounds like a problem with either Home Connect or SingleKey ID. Please contact the Home Connect team at either:
* https://www.home-connect.com/global/service/contact-customer-service
* https://developer.home-connect.com/support/contact

This plugin does not have any involvement with the authorization process after it has provided the URL, until the authorization is successfully completed.

**Comment by cros13** [comment]
In my case I found that the SingleKey ID page was not redirecting after sign in due to an issue with the Content Security Policy directive set on the SingleKey ID site. As a workaround I just ticked "stay logged in", opened the browser inspect and manually clicked the callback URL, where I was able to authorise.
