### ISSUE TITLE
Home Connect API Error

### ISSUE THREAD

**Issue by mistertropi** [thoukydides/homebridge-homeconnect#137]
### Description of Issue

Hallo Guys,

Yesterday i get the following issue: Home connect API error: getaddrinfo EAI Again api.home-connect.com

i tried to get a new device id By adding a new device. But nothing changed in the log.

please help

thanks 

### Expected Behaviour

Please give me a Solution

### Steps to Reproduce

Update

### Plugin Version

0.28.0

### Environment

- OS:
- Node:
- Homebridge:
hoobs:4.3

### Diagnostic Checks

- [ ] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [ ] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [ ] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [ ] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [ ] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
[ERROR] Home Connect API error: getaddrinfo EAI_AGAINI.Home-connect.com
```

### Configuration

```json
clientid",
  "language" : {
    "api" : "en-GB"
  },
  "platform" : "HomeConnect",
  "plugin_map" : {
    "plugin_name" : "homebridge-homeconnect"
  },
  "simulator" : false
```

**Comment by thoukydides** [comment]
I also see that you are using HOOBS. This is a Homebridge plugin, not a HOOBS plugin.

Since this appears to be an issue with the server environment on which you are running the plugin, I am closing this issue. If you require further assistance with this issue then I suggest contacting HOOBS support.
