### ISSUE TITLE
Dishwasher Half Load Option 

### ISSUE THREAD

**Issue by r33ce15** [thoukydides/homebridge-homeconnect#138]
### Description of Enhancement

Been loving being able to get my dishwasher into HomeKit and remote starting it and having the use of automation triggers once finished and to remind me to to up salt etc! 

One feature would be great to have and looking through home connect api seems its an option available would be to have the half load function on the dishwasher available in HomeKit I'm not sure how this would work I would see it as another switch like pre rinse that can be toggled on 

Let me know if this is something you think is plausible or may its in there already and I have missed it!

Thanks 

### Home Connect Mapping

https://api-docs.home-connect.com/programs-and-options?#dishwasher_half-load-option

### Home Connect Appliance(s)

Siemens iQ300 Dishwasher

**Comment by r33ce15** [comment]
Thanks for fast response! 

Oh I see I notice in my config I just have "auto" under programs so it must be auto building based off the home connect setup 

I'll dig into this as see it has been all documented thanks for pointing me to the page

**Comment by thoukydides** [comment]
The default "auto" setting means that a HomeKit Switch is created for each program that the appliance supports, but it does not specify any of the program options. The appliance will just use whatever its default options are for each program.

You can customise the program switches to specify whatever options you require. Multiple HomeKit switches can be configured for each program to use different options.

**Comment by r33ce15** [comment]
So is it possible to have add programs auto and then also add custom switches with program options specified or if you manually specify you need to specify them all?

**Comment by thoukydides** [comment]
Closing this feature request since the requested functionality already exists.
