### ISSUE TITLE
Would you pleeeeeese make this integration availible for Home Assistant.io?

### ISSUE THREAD

**Issue by YRRK** [thoukydides/homebridge-homeconnect#14]
#### Description of Enhancement

Dear A. thoukydides, as the title says. Would you please make this plugin/integration also useable for the Home Assistant community? See https://www.home-assistant.io/
Their platform is really really great and they mis the HomeConnect integration. I mis it very much there :-) They have made all info availible for developers to jump right in. HomeConnect would be great! If you do so, please make an 'official" integration for the wide adoption, not a community add-on, this is rather more someting for expericed users.
Thank you for writing this homebridge plug-in! It's really great!

#### Home Connect Appliance(s)

Oven, dishwasher, coffeemachine.

**Comment by thoukydides** [comment]
Sorry, I only use HomeKit for my home automation. I do not use Home Assistant and have no plans to do so. Hence, I will not be developing a plugin for it.

**Comment by YRRK** [comment]
> Sorry, I only use HomeKit for my home automation. I do not use Home Assistant and have no plans to do so. Hence, I will not be developing a plugin for it.

Thanks for your answer. By the way, I used to use homebrige before. But homeassistant is far more advanced and stable too. It can couple all your devices to homekit in a more friendly manner. If you haven't tried it before I can very much recommend it over homebridge for homekit bridging!

**Comment by thoukydides** [comment]
Looks like other people have already been working on this anyway:
* [homeassistant-bosch_dryer](https://github.com/gkreitz/homeassistant-bosch_dryer)
* [homeassistant-bosch_washer](https://github.com/cotwild/homeassistant-bosch_washer)
* [homeassistant-bosch-oven](https://github.com/cotwild/homeassistant-bosch-oven)

**Comment by YRRK** [comment]
Oh wow you found this. It's a non-official integration i see hmzzz and incomplete, missing de diswasher and coffee machine. Need to think about this... :-)
