### ISSUE TITLE
Authorization Link in UI Config invalid

### ISSUE THREAD

**Issue by Skjall** [thoukydides/homebridge-homeconnect#151]
### Description of Issue

![image](https://github.com/thoukydides/homebridge-homeconnect/assets/13360352/97a7f2b2-7add-4c51-9d3b-de2e5477942c)

Link label in the settings for the plugin shows a promise instead of the correct link.
Link is wrong as well: https://10.x.x.x/[object%20Promise]

### Expected Behaviour

Working link with the correct label. Maybe a missing await.

### Steps to Reproduce

Open HomeConnect Config in the UI.

### Plugin Version

homebridge-homeconnect v0.29.3

### Environment

- OS: Ubuntu Focal Fossa (20.04.5 LTS)
- Node: v18.16.1
- Homebridge: v1.6.1

### Diagnostic Checks

- [ ] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [ ] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [ ] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [ ] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [ ] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
No Relevant log output.
```

### Configuration

```json
Relevant section:

        {
            "clientid": "XXXXXXXXXXXXXXXXXXXXXXXX",
            "simulator": false,
            "language": {
                "api": "de-DE"
            },
            "SIEMENS-HS658GXS6-XXXX": {
                "addprograms": "none",
                "programs": []
            },
            "SIEMENS-SX678X26TE-XXXX": {
                "addprograms": "none",
                "programs": []
            },
            "SIEMENS-TI909701HC-XXXX": {
                "addprograms": "none",
                "programs": []
            },
            "SIEMENS-WT7YH780-XXXX": {
                "addprograms": "none",
                "programs": []
            },
            "SIEMENS-WM6YH790-XXXX": {
                "addprograms": "none",
                "programs": []
            },
            "platform": "HomeConnect"
        },
```

**Comment by thoukydides** [comment]
Thank you for reporting that issue.

Unfortunately, this plugin is currently halfway through a significant rewrite. I have not yet got around to the homebridge-config-ui-x handling, so it is currently a bit of a hack to glue its old code to the new stuff elsewhere.

As you suggest, a missing `await` is part of the cause for the authorisation URI not being displayed correctly, but not quite the whole story. I will fix that specific issue, but the homebridge-config-ui-x support is still going to be a little rough around the edges until I finish the rewrite. For example, the authorisation URI is only valid for 30 minutes (with the current Home Connect authorisation server behaviour), but the GUI configuration will still show the invalid URI after that. I don't think it is worth putting more bandaids on the current hack to address that shortcoming.

**Comment by Skjall** [comment]
Ahh, got it. Don't worry about it. I'm looking forward to the rewrite. Thanks!
