### ISSUE TITLE
Triggers not appear in Apple home

### ISSUE THREAD

**Issue by raphaeldavid** [thoukydides/homebridge-homeconnect#153]
### Description of Issue

In Homebridge, I see
- Salt low
- Rinse aid low
- Program Finished
but I don't see them in Apple Home

### Expected Behaviour

I want to see them in Apple Home, in order to perform automations

### Steps to Reproduce

N/A

### Plugin Version

0.29.5

### Environment

- OS: Ubuntu Focal Fossa (20.04.5 LTS)
- Node: v18.13.0
- Homebridge: v1.6.1

### Home Connect Appliance(s)

Thermador Dishwasher (E-Nr: DWHD770WFP/01)

### HomeKit App(s)

Apple home

### Diagnostic Checks

- [ ] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [ ] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [ ] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [ ] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [ ] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
N/A
```

### Configuration

```json
{
            "clientid": "...",
            "simulator": false,
            "language": {
                "api": "en-US"
            },
            "THERMADOR-DWHD770WFP-68A40E09C239": {
                "addprograms": "custom",
                "programs": [
                    {
                        "name": "Mode - Auto",
                        "key": "Dishcare.Dishwasher.Program.Auto2",
                        "selectonly": false,
                        "options": {
                            "Dishcare.Dishwasher.Option.VarioSpeedPlus": true
                        }
                    }
                ]
            },
            "platform": "HomeConnect"
        },
```

**Comment by thoukydides** [comment]
These events are presented to HomeKit at [Stateless Programmable Switch services](https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Mapping#stateless-programmable-switch-services-for-events). The Apple Home app shows these as numbered buttons that support automations from their Single Press action:

![image](https://github.com/thoukydides/homebridge-homeconnect/assets/4775242/bcab40f8-70b8-45fb-9f35-780e4c97bcfa)

Some other HomeKit apps show descriptive labels for these buttons, but with the Apple Home app you need to know how the events map to the numeric labels. For a dishwasher appliance these are:
1. Program Finished
2. Program Aborted
3. Salt Low
4. Rinse Aid Low
