### ISSUE TITLE
409 Conflict DishWasher SN61IX12TE

### ISSUE THREAD

**Issue by Jamyz** [thoukydides/homebridge-homeconnect#155]
### Description of Issue

I dont no why have this error now. Before all good.  
[8/3/2023, 3:39:53 PM] [homebridge-homeconnect] [Lave-vaisselle ] [GET status] Home Connect Status Code Error: [409 Conflict] HomeAppliance connection initialization failed [SDK.Error.HomeAppliance.Connection.Initialization.Failed]
[8/3/2023, 3:39:53 PM] [homebridge-homeconnect] [Lave-vaisselle ] GET /api/homeappliances/40210038685600XXXXX/status
I try with new update  v0.29.6 and nothing too.

XXXXXXXX to change

### Expected Behaviour

Works

### Steps to Reproduce

Nothing

### Plugin Version

 v0.29.6

### Environment

- OS: CasaOs v.0.4.4
- Node: [v18.13.0]
- Homebridge: v18.13.0

CasaOS + HomeBridge running under Docker

### Home Connect Appliance(s)

Siemens SN61IX12TE

### HomeKit App(s)

Apple HomeKiot

### Diagnostic Checks

- [ ] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [ ] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [ ] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [ ] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [ ] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
[8/3/2023, 3:39:53 PM] [homebridge-homeconnect] [Lave-vaisselle ] [GET status] Home Connect Status Code Error: [409 Conflict] HomeAppliance connection initialization failed [SDK.Error.HomeAppliance.Connection.Initialization.Failed]
[8/3/2023, 3:39:53 PM] [homebridge-homeconnect] [Lave-vaisselle ] GET /api/homeappliances/40210038685600XXXXX/status
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge C971",
        "username": "XX:XX:XX:XX:XX",
        "port": 5465465,
        "pin": "000000",
        "advertiser": "bonjour-hap"
    },
    "accessories": [
        {
            "name": "Jamyz-PC",
            "manufacturer": "homebridge-wol",
            "model": "NetworkDevice",
            "host": "192.168.1.XXXX",
            "pingInterval": 2,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "pingCommandTimeout": 0,
            "mac": "XX:XX:XX:XX:XX",
            "broadcastAddress": "192.168.1.XXX",
            "startCommandTimeout": 0,
            "wakeGraceTime": 45,
            "wakeCommandTimeout": 0,
            "shutdownCommand": "net rpc shutdown --ipaddress 192.168.1.XXX --user USER%Pass",
            "shutdownGraceTime": 15,
            "shutdownCommandTimeout": 0,
            "logLevel": "Info",
            "returnEarly": false,
            "_bridge": {
                "username": "XX:XX:XX:XX:XX",
                "port": 1231321321
            },
            "accessory": "NetworkDevice"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "clientid": "311111111111111111111111111111111111111111111111",
            "simulator": false,
            "language": {
                "api": "es-ES"
            },
            "2222222222222222222222": {
                "addprograms": "none",
                "programs": []
            },
            "_bridge": {
                "username": "XX:XX:XX:XX:XX",
                "port": 36007
            },
            "platform": "HomeConnect"
        },
        {
            "country": "FR",
            "language": "fr-FR",
            "auth_mode": "token",
            "refresh_token": "1111111111111111111111111111111",
            "username": "11111111111111111@gmail.com",
            "password": "11111111111111",
            "platform": "LGThinQ",
            "_bridge": {
                "username": "XX:XX:XX:XX:XX",
                "port": 56053
            },
            "devices": [
                {
                    "id": "ccccccccccccccccccccccc",
                    "name": "Aire Ivan",
                    "type": "AC",
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": true,
                    "ac_temperature_unit": "C"
                },
                {
                    "id": "cccccccccccccccccc",
                    "name": "Aire Salon",
                    "type": "AC",
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": true,
                    "ac_temperature_unit": "C"
                },
                {
                    "id": "cccccccccccccccccccccccccc",
                    "name": "Aire Marie",
                    "type": "AC",
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": true,
                    "ac_temperature_unit": "C"
                }
            ],
            "thinq1": true,
            "refresh_interval": 60
        }
    ],
    "disabledPlugins": [
        "homebridge-meross"
    ]
}
```

**Comment by thoukydides** [comment]
According to the [API documentation](https://api-docs.home-connect.com/general/?#api-errors), that error is:

Code | Short Description | Long Description
-- | -- | --
409 | SDK.Error.HomeAppliance.Connection.Initialization.Failed | <ul><li>HomeAppliance is offline<li>HomeAppliance did not respond to connection initialization requests in time, it might be offline<li>HomeAppliance did not respond in time, it might by offline</ul>

It is possible that this is an issue with the Home Connect cloud services, although I am [not seeing that error myself](https://homeconnect.thouky.co.uk/). Hence, it is most likely to be an issue with your appliance's connection to the cloud servers. A good test is to disable Wi-Fi on your phone (forcing it to use a cellular connection to the cloud servers rather than connecting directly to the appliance) and then controlling the appliance with the official Home Connect app.

This does not appear to be a problem with the plugin itself. There really isn't anything that it can do if the cloud services return errors in response to basic queries...
