### ISSUE TITLE
CoffeeMaker: Percentage of milk option missing

### ISSUE THREAD

**Issue by VanjaMia** [thoukydides/homebridge-homeconnect#157]
### Description of Enhancement

In the Home Connect app and on the Siemens coffee maker, you can select the percentage of milk for milky coffee, such as latte macchiato, cappuccino and so on. Unfortunately, this is not possible in the plugin. Would be great if this option was also available in the plugin.
![IMG_8518](https://github.com/thoukydides/homebridge-homeconnect/assets/141960041/93ea1750-ae0d-4584-a245-d37342a32605)
![IMG_8517](https://github.com/thoukydides/homebridge-homeconnect/assets/141960041/b33de7e7-271c-42a3-bfac-22d713d93420)
![IMG_8519](https://github.com/thoukydides/homebridge-homeconnect/assets/141960041/6423b7b4-2f0b-454a-99eb-c316b7199467)

### Home Connect Appliance(s)

Siemens CoffeyMaker EQ700 TP707D06/02

**Comment by thoukydides** [comment]
Thus plugin already supports all program options that are exposed by the Home Connect API. If you refer to the [documentation](https://api-docs.home-connect.com/programs-and-options/?#coffee-machine) you will see that the only supported options for coffee makers are:
* ConsumerProducts.CoffeeMaker.Option.BeanAmount
* ConsumerProducts.CoffeeMaker.Option.FillQuantity
* ConsumerProducts.CoffeeMaker.Option.CoffeeTemperature
* ConsumerProducts.CoffeeMaker.Option.BeanContainerSelection
* ConsumerProducts.CoffeeMaker.Option.FlowRate
* ConsumerProducts.CoffeeMaker.Option.MultipleBeverages
* ConsumerProducts.CoffeeMaker.Option.HotWaterTemperature

You will need to [ask the Home Connect team](https://developer.home-connect.com/support/contact) to add a milk percentage option. If that gets added then it will be supported automatically by this plugin; no code changes required.

**Comment by VanjaMia** [comment]
Ok thanks for the information. I've made a request to the home connect developer team

**Comment by VanjaMia** [comment]
Answer from Home Connect team
![image](https://github.com/thoukydides/homebridge-homeconnect/assets/141960041/21129fe9-e13c-4d8f-ba9e-69379be97837)
