### ISSUE TITLE
This plugin gets other plugins unresponsive within Apple Home

### ISSUE THREAD

**Issue by ChrWi** [thoukydides/homebridge-homeconnect#164]
### Description of Issue

My homebridge has 
homebridge-fritz-platform v6.0.19
homebridge-denon-heos v2.9.7
homebridge-xiaomi-fan v1.5.9
homebridge-webos-tv v2.4.1
installed. After configuring homeconnect plugin and restart everything looks good and is working inside homebridge-ui-x, however my devices linked to above plugins have status „no response“ within Apple Home app. After removing the homeconnect configuration and restart, all devices are fine again within Apple Home app.

### Expected Behaviour

Everything fine within Apple Home app

### Steps to Reproduce

?

### Plugin Version

v0.29.7

### Environment

- OS: rasp buster
- Node: 18.16
- Homebridge: 1.6.1

### Home Connect Appliance(s)

Neff T66BT6QN2

### HomeKit App(s)

Apple Home, based onOS17

### Diagnostic Checks

- [X] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [X] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [X] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [X] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [X] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
-
```

### Configuration

```json
-
```

**Comment by thoukydides** [comment]
I don’t see that issue myself, so without more information there’s nothing I can do about it. There shouldn’t been any interaction with other plugins unless Homebridge is crashing… which would be obvious from its log file.

Do the Home Connect appliances show in the Home app? Do they work or are they also showing No Response like the other plugins?

Please provide a Homebridge log file for the failing scenario, with both Homebridge debug (via the `-D` command line switch) and HAP debug (via the `DEBUG=*` environment variable) logging enabled.

**Comment by ChrWi** [comment]
I removed the homebridge from Homekit. In addition I updated my n / npm versions. 
Finally I added the homebridge again to Homekit and got 2 switches for my Neff hood. 
I will do some further checks over the next days and let you know if there are issues appearing again.

**Comment by ChrWi** [comment]
No more issues on my side thus closing this issue.
