### ISSUE TITLE
Dryer AutoSense

### ISSUE THREAD

**Issue by darrenmcuk** [thoukydides/homebridge-homeconnect#188]
### Description of Enhancement

It would be great to be able to trigger the dryer autosense

https://ifttt.com/hc_dryer/actions/dryer_select_connected_dry_program

as IFTTT does. Any chance? My wife uses this endlessly for sync between the washing machine and dryer.

Thanks

**Comment by thoukydides** [comment]
If that options is supported via the Home Connect API then it is already supported by this plugin. You can find details of programs and options supported by the API here (although note that not all options supported by the API are available on all appliances):
https://api-docs.home-connect.com/programs-and-options/?#dryer

IFTTT does not use the public Home Connect API. There are quite a few things that IFTTT supports that cannot be achieve via the public API. This might be one of those features.

If it is not already supported by your appliance via the Home Connect API then it will need to be added by the Home Connect team; request the feature here:
https://developer.home-connect.com/support/contact
