### ISSUE TITLE
Fridge freezer - Door Sensor cannot be renamed

### ISSUE THREAD

**Issue by IWCaldwell** [thoukydides/homebridge-homeconnect#196]
### Description of Issue

Added 3 new sensors for the Refridgerator Door, Chiller Common Door and Freezer Door.
I see these added into HomeKit, however, I cannot rename the doors.  As soon as I change it in HomeKit the name reverse back to "Fridge Freezer" for all the door sensors which makes it very hard to determine which door has been opened

### Expected Behaviour

Doors should be named better but also have the ability to change the names like every other accessory I have, not sure why I can't change the name of any of these sensors.

### Steps to Reproduce

Added a BOSCH Fridge with the following settings:

"Door": false,
"Event Buttons": true,
"Internal Light": true,
"Freezer Super Mode": true,
"Fresh Mode": true,
"Refrigerator Super Mode": true,
"Vacation Mode": true,
"Eco Mode": true,
"Sabbath Mode": false,
"Ice Dispenser": true,
"Freezer Door": true,
"Chiller Common Door": true,
"Refrigerator Door": true

I see the 3 door sensors listed in home, all are listed as "Fridge freezer".  When I try and rename them they instantly change back to "Fridge freezer".  I can't tell the difference between the Refridgerator Door vs the two other doors.  Not sure why I can't rename them like I can with other accessories, the name just reverts back.

### Plugin Version

v0.36.0

### Environment

- OS: Raspbian GNU/Linux Bookworm (12)
- Node: v20.10.0
- Homebridge: v1.7.0

### Home Connect Appliance(s)

BOSCH B36CL80SNS

### HomeKit App(s)

Apple TV, iPad, iPhone, Macbook Pro

### Diagnostic Checks

- [ ] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [ ] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [ ] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [ ] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [ ] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
[28/12/2023, 21:44:17] [homebridge-homeconnect] [Fridge freezer] Door open
[28/12/2023, 21:44:29] [homebridge-homeconnect] [Fridge freezer] Door closed
[28/12/2023, 21:44:33] [homebridge-homeconnect] [Fridge freezer] Door open
[28/12/2023, 21:44:49] [homebridge-homeconnect] [Fridge freezer] Door closed
```

### Configuration

```json
{
    "clientid": "******************************",
    "simulator": false,
    "language": {
        "api": "en-US"
    },
    "BOSCH-B36CL80SNS-******": {
        "features": {
            "Door": false,
            "Event Buttons": true,
            "Internal Light": true,
            "Freezer Super Mode": true,
            "Fresh Mode": true,
            "Refrigerator Super Mode": true,
            "Vacation Mode": true,
            "Eco Mode": true,
            "Sabbath Mode": false,
            "Ice Dispenser": true,
            "Freezer Door": true,
            "Chiller Common Door": true,
            "Refrigerator Door": true
        }
    },
    "_bridge": {
        "username": "*******",
        "port": ******
    },
    "platform": "HomeConnect"
}
```

**Comment by thoukydides** [comment]
> I see the 3 door sensors listed in home, all are listed as "Fridge freezer".

That’s not the case for me. The Home app shows them with their different type names:

![IMG_0628](https://github.com/thoukydides/homebridge-homeconnect/assets/4775242/80b366f6-dc21-4e18-9a2b-f0205b4d77a0)

![IMG_0627](https://github.com/thoukydides/homebridge-homeconnect/assets/4775242/39f8cd94-aad3-49cb-bbb3-7df1c02fcedc)

![IMG_0626](https://github.com/thoukydides/homebridge-homeconnect/assets/4775242/87aa0906-9c7d-472d-913f-baa24f81b7ad)

> ```
> [28/12/2023, 21:44:17] [homebridge-homeconnect] [Fridge freezer] Door open
> [28/12/2023, 21:44:29] [homebridge-homeconnect] [Fridge freezer] Door closed
> [28/12/2023, 21:44:33] [homebridge-homeconnect] [Fridge freezer] Door open
> [28/12/2023, 21:44:49] [homebridge-homeconnect] [Fridge freezer] Door closed
> ```

The use of `Door` in the log messages for all the different types of door is an oversight. I will fix that in the next release.

> however, I cannot rename the doors.
> …
> but also have the ability to change the names like every other accessory I have, not sure why I can't change the name of any of these sensors.

This was a deliberate choice to make the `ConfiguredName` characteristics read-only. I will consider changing them to be writable.

**Comment by IWCaldwell** [comment]
Here is an example of me trying to rename it on my MacBook Pro, does the same on iPads, iPhones, etc... I change the name, when I close out it remains at the original name.  When I go to anything else like my enphase solar done through homebridge as well it renames just fine
![Renaming](https://github.com/thoukydides/homebridge-homeconnect/assets/44706131/4fd06cbf-465f-4b91-a8c0-6663da7dd601)

**Comment by thoukydides** [comment]
Yes, I know these services don't support being renamed. As I said, that was a deliberate implementation choice... which I might reconsider.

I cannot reproduce the issue of all the doors being called "Fridge freezer" in my testing. They each have appropriate unique names when I try it. I don't have an actual Home Connect fridge freezer to test against, so am having to mock it up, but that shouldn't make any difference.

The implementation of service names in this plugin hasn't materially changed since v0.27.0, when I first implemented a workaround for the new behaviour in the iOS 16 version of the Apple Home app... and is similar to how most plugins have handled it. However, I noticed that a [different approach](https://github.com/homebridge/homebridge/issues/3210#issuecomment-1837193443) was suggested on homebridge/homebridge#3210 last month that might be worth looking into.

**Comment by robbydek** [comment]
Wasn’t sure if it was a bug or not, but I noticed the something similar.  None of my switches are named for their function and I can’t rename them.

this is my first version ( got my fridge today), so maybe they changed something.

**Comment by thoukydides** [comment]
I have made quite a few changes to the handling of service names in [v0.37.0](https://github.com/thoukydides/homebridge-homeconnect/releases/tag/v0.37.0). These include making the `ConfiguredName` writable, and attempting to avoid overwriting any name that has been changed within HomeKit.

It probably won't do anything about services all having the appliance name, rather than the unique names set by the plugin. I have no idea why that happens, and cannot reproduce it to debug.

**Comment by IWCaldwell** [comment]
Well it's getting a little better now, the names have changed in my HomeKit to:

Fridge freezer Chiller Common Door
Fridge freezer Freezer Door
Fridge freezer Refrigerator Door

Still can't be renamed like other Homebridge accessories, but it's not just the name of the appliance now so I can tell the difference between each door.

<img width="501" alt="image" src="https://github.com/thoukydides/homebridge-homeconnect/assets/44706131/6c986d81-9bfa-47e1-bbaf-2046cd05f755">

**Comment by IWCaldwell** [comment]
Oh nice, like the new prefix removal feature:
<img width="744" alt="image" src="https://github.com/thoukydides/homebridge-homeconnect/assets/44706131/57492370-0493-44a4-a802-187257ae898b">

Looks nicer looking at all the features now:

<img width="476" alt="image" src="https://github.com/thoukydides/homebridge-homeconnect/assets/44706131/fefb9212-0cc3-4114-9f3e-9e98fe09c6d3">

If we could set a Prefix name in HomeBridge that would be awesome instead of the default Fridge Freeze, such as Main Fridge, Basement Fridge, Garage Fridge, incase we had multiple.

**Comment by thoukydides** [comment]
The appliance name used as a prefix is the one set in the Home Connect app, as used for the initial accessory name. Adding yet another way to rename the appliance seems rather pointless.

Renaming services within HomeKit now works for me, so if you want me to investigate that you will need to provide more detail, including a Homebridge for file for the period you tried to rename the services. For this issue please enable both Homebridge debug logging (enabled with the `-D` command line option) and HAP debugging (enabled with the `DEBUG=*` environment variable).

**Comment by robbydek** [comment]
Thanks.  Not sure if it was my switchmate plugin or not, now I see what the switches, etc are for vs just the appliance name.

**Comment by S-Mario987** [comment]
Thank you so much for your support! Now it’s working well! 😊😊😊

**Comment by thoukydides** [comment]
It looks like this issue is resolved, so I am closing it.
Feel free to raise a new issue if you still have problems.

**Comment by IWCaldwell** [comment]
It is not resolved, still cannot rename any of the items and was trying to get debug logs and post them here, but ok

**Comment by thoukydides** [comment]
OK, sorry. I will wait for the logs...

**Comment by IWCaldwell** [comment]
Sorry taking me a little longer then expected, my Raspberry Pi has too much running on it and the logs are a little crazy, trying to get Homebridge installed on a laptop to test with and having to disable firewalls, etc...  Will try and get them to you today or tomorrow at the latest

**Comment by thoukydides** [comment]
Just a thought @IWCaldwell, before you waste time collecting logs. I suspect that the issue you are seeing is that HomeKit has cached the old read-only permissions on the `Configured Name` services, and is ignoring the update from Homebridge.

It might be worth trying force-quitting the Apple Home app and restarting it before trying again. (Occasionally it is also necessary to reboot all iPhone/iPad/etc devices sharing the HomeKit account to resolve such caching issues.)

**Comment by IWCaldwell** [comment]
@thoukydides You are correct, that did the trick, I can rename stuff now.  Thank you so much!!!
