### ISSUE TITLE
Bug when active program „Change water filter“

### ISSUE THREAD

**Issue by Kohle81** [thoukydides/homebridge-homeconnect#22]
Hi,

I made the following observation.  The message that the filter needs to be changed appears on my coffee machine.  As long as the message on the coffee machine was not confirmed, the plugin crashes when a switch is activated in HomeKit.

T. --
Feb 26 21:33:27 raspberrypi homebridge[13854]: [2/26/2020, 21:33:27] [HomeConnect] [Kaffeemaschine] On
Feb 26 21:33:27 raspberrypi homebridge[13854]: [2/26/2020, 21:33:27] [HomeConnect] [Kaffeemaschine] Manual mode (remote start allowed, being operated locally)
Feb 26 21:33:31 raspberrypi homebridge[13854]: [2/26/2020, 21:33:31] [HomeConnect] [Kaffeemaschine] Remote operation enabled (remote start allowed)
Feb 26 21:34:12 raspberrypi homebridge[13854]: [2/26/2020, 21:34:12] [HomeConnect] [Kaffeemaschine] SET Off
Feb 26 21:34:12 raspberrypi homebridge[13854]: [2/26/2020, 21:34:12] [HomeConnect] [Kaffeemaschine] Home Connect API error: BSH.Common.Setting.PowerState currently not available or writable [SDK.Error.InvalidSettingState]
Feb 26 21:34:12 raspberrypi homebridge[13854]: [2/26/2020, 21:34:12] [HomeConnect] [Kaffeemaschine] SET BSH.Common.Setting.PowerState=BSH.Common.EnumType.PowerState.StandbyFeb 26 21:34:12 raspberrypi homebridge[13854]: [2/26/2020, 21:34:12] [HomeConnect] [Kaffeemaschine] PUT https://api.home-connect.com/api/homeappliances/SIEMENS-TI9555X1DE-68A40E325678/settings/BSH.Common.Setting.PowerState
Feb 26 21:34:16 raspberrypi homebridge[13854]: [2/26/2020, 21:34:16] [HomeConnect] [Kaffeemaschine] Inactive (Ready)
Feb 26 21:36:43 raspberrypi homebridge[13854]: [2/26/2020, 21:36:43] [HomeConnect] [Kaffeemaschine] Manual mode (remote start allowed, being operated locally)
Feb 26 21:36:48 raspberrypi homebridge[13854]: [2/26/2020, 21:36:48] [HomeConnect] [Kaffeemaschine] Remote operation enabled (remote start allowed)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thoukydides** [comment]
The log snippet that you have provided does not show a crash.

From that short excerpt it looks like the appliance was switched on, finished its initialisation and indicated its `Ready` status. You then tried to switch it off from HomeKit and the Home Connect API reported:
```
BSH.Common.Setting.PowerState currently not available or writable [SDK.Error.InvalidSettingState]
```

The plugin would have then reported the failure back to HomeKit and it continued running correctly.

It does not appear that the HomeConnect API provided any information that would have allowed that error to be avoided, and the plugin handled the error correctly when it was returned.

What am I missing?
Why do you think this behaviour is a bug?
What are you expecting the plugin to do differently?

**Comment by thoukydides** [comment]
It is also worth noting that the Home Connect API does not provide any information about the water filter:
https://developer.home-connect.com/docs/monitoring/availabilitymatrix

**Comment by Kohle81** [comment]
Hello, maybe I didn't express myself well because of bad English.  I wanted to say that if the message "Water filter" is active and then the coffee machine is switched off via HomeKit, the plugin then no longer responds.  The power switch then stops responding and the switch remains unresponsive even after the water filter has been confirmed.  Restarting the homebridge will fix the problem.  However, it is not too dramatic for me if the situation remains as I only have to change the water filter every 4 weeks.  It wasn't meant badly by me, I just wanted to point out my observation.  Bug was probably the wrong word for it.

> Am 27.02.2020 um 04:58 schrieb Alexander Thoukydides <notifications@github.com>:
> 
> What are you expecting the plugin to do differently?

**Comment by thoukydides** [comment]
OK, but that's not what the log that you provided shows.

The only operation attempted in that log is switching the appliance OFF. That request is rejected by the Home Connect API.

If you are able to provide a log (preferably with debug enabled) that actually shows the problem that you describe then I can investigate.

**Comment by Kohle81** [comment]
Hi,


I have now found that the power switch sometimes does not respond to me, even without a program issuing a message.

But I doesn‘t find something in log file with „sudo cat /var/log/syslog“

Which log file do you need?

I don‘t know why the Power Switch crashes....

I have the plugin in a separate instsnce of homebridge. How can I start homebridge in debug mode in this constellation?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thoukydides** [comment]
> I have now found that the power switch sometimes does not respond to me, even without a program issuing a message.

Please can you provide a more detailed explanation of the problem. It is still not clear to me precisely how it is failing for you.

Presumably you are referring to the HomeKit Switch characteristic that this plugin creates to control the plugin's power.

Are you controlling this from an app or from Siri?
If it is from a HomeKit app, then which one are you using?
What does the app show when "it does not respond", e.g. does the switch return to its original position and is any error state indicated?
Do other HomeKit apps behave the same?

What do you mean by "without a program issuing a message"? Do you mean the HomeKit app? Or the Homebridge log file?

Does the failure occur switching the appliance on from HomeKit (when currently switched off), or switching it off from HomeKit (when currently switched on), or both?

Does the switch status in HomeKit apps change correctly if you switch the appliance on or off manually?

> But I doesn‘t find something in log file with „sudo cat /var/log/syslog“

Is that where the Homebridge log is normally written on your installation?

> Which log file do you need?

The Homebridge log file for the instance running this plugin.

The short log snippet that you provided is from the correct log file. However, it would be more useful with additional logging enabled:
* Homebridge debug level logging enabled, by adding the `-D` option to the Homebridge command line. This is necessary to see all exchanges with the Home Connect servers.
* HAP-NodeJS logging enabled, by setting `DEBUG=*` in the Homebridge environment. This is necessary to see what commands HomeKit is sending to the plugin, and what responses are returned.

For example: `DEBUG=* homebridge -D  -P plugindir -U configdir`

From the descriptions that you have provided so far it is not clear whether it is the HomeKit interface or the Home Connect interface that might be failing. The short log excerpt you provided shows the plugin correctly forwarding an error from the Home Connect API back to HomeKit - as far as I can see the plugin is behaving correctly.

However, I am struggling to tie-up what that log shows with the descriptions that you have provided. A more complete log file, and a clearer description or the precise sequence of events that the log file covers, would help.

> I don‘t know why the Power Switch crashes....

I interpret "crashes" to mean that the Homebridge process is terminating. Is that what you are seeing? Or do you mean something else?

> I have the plugin in a separate instsnce of homebridge. How can I start homebridge in debug mode in this constellation?

I have no idea how you have installed Homebridge, so cannot offer any advice on how to change its configuration.

**Comment by Kohle81** [comment]
The error has not reappeared ..... Maybe there were other circumstances, in any case the plugin runs reliably with me.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
