### ISSUE TITLE
Display remaining time until finished

### ISSUE THREAD

**Issue by urbanhaas** [thoukydides/homebridge-homeconnect#225]
### Description of Enhancement

I have been a happy user of Homebridge and this excellent plug-in for years. You've also been enhancing it nicely.

I see messages in Homebridge log (or Homeconnect log) showing remaining time:
[1/12/2024, 3:54:19 PM] [HomeConnect] [Bosch Dryer] Program has 17 minutes remaining
[1/12/2024, 3:55:19 PM] [HomeConnect] [Bosch Dryer] Program has 16 minutes remaining

It would be great of this status could be exposed to the device in Home.app.

### Home Connect Mapping

BSH.Common.Option.RemainingProgramTime seems to show this.

### HomeKit Mapping

Potentially HMCharacteristicTypeRemainingDuration
HMCharacteristicTypeProgramMode might also be nice

### Home Connect Appliance(s)

Bosch Washer (E-Nr: WAW285H2UC/20), Bosch Dryer (E-Nr: WTG865H2UC/01)

**Comment by thoukydides** [comment]
This plugin already exposes the remaining duration to HomeKit. This clearly listed in the [supported functionality](https://github.com/thoukydides/homebridge-homeconnect/wiki/Functionality)

As the [HomeKit mapping](https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Mapping#extra-active-program-switch-characteristics) explains this is implemented using a `Remaining Duration` characteristic on the Active Program `Switch` service.
However, you will need to use a [third-party HomeKit app](https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Apps) to see it. I recommend using [The Eve App](https://www.evehome.com/en/eve-app).

Apple’s Home app will only show duration for a `Irrigation System` or `Valve` services, neither of which are appropriate to use for Home Connect appliances. I have explained my reasons for not implementing those many times; see #48, #68, #114, … and just 5 days ago in #218.
