### ISSUE TITLE
Feature request: IFTTT Support for existing devices

### ISSUE THREAD

**Issue by Nastras** [thoukydides/homebridge-homeconnect#23]
Hello @thoukydides,

i have an idea and wanted to ask you what you think about it and if you would like to implement it.
You have already written that there are other possibilities to control a device via ifttt than via the normal home-connect api.

Wouldn't it be possible to add an option to your plugin in config.json that allows you to add additional switches to the device that call ifttt functions? These switches should be user definable in config.json with the appropriate ifttt automations similar to the ifttt plugin.

This would give us the big advantage that additional options are available that are not available through the normal homeconnect api.

It is just an idea and I am aware that it is not easy to implement and I am not sure if there is anything technically wrong with it. So I just wanted to share this idea with you :-)

But I think it could be an enrichment for the plugin.

Best Regards 
Nastra

**Comment by thoukydides** [comment]
What benefit would this give beyond configuring those switches using the [homebridge-ifttt](https://www.npmjs.com/package/homebridge-ifttt) plugin?

**Comment by Nastras** [comment]
It would be easier for others in the home to understand the device. Especially to explain to your wife that if you want to start a program at the washing machine you have to use the washing machine.

If you want to switch off the washing machine, you don't have to use the washing machine, but an extra device with a switch that switches off the washing machine. 

The acceptance factor of a woman is relatively low if it is too complicated, so I hoped that with the ifttt integration in your plugin you can add an extra switch to the device X which is displayed as power or custom charistic.

This is the background of my idea. But I think there are certainly other use cases that are not covered by the homeconnect api.

**Comment by thoukydides** [comment]
Integrating IFTTT in the transparent way that you are suggesting would be too complicated and would lead to feature-creep that I am not willing to support.

For example, it would require the power switch to use the existing Home Connect API for switching appliances on, but depending on the appliance type would either need to use the Home Connect API or IFTTT to switch it off. I might have considered this if it didn't also rely on the end-user manually creating appropriate IFTTT applets and then configuring this plugin to match.

It gets even more complicated when the HomeKit characteristics also need to be updated from IFTTT triggers via webhooks, e.g. indicating i-Dos low.

The alternative of just creating switches for each IFTTT applet would not significantly improve the user experience - if anything it would make the existing long list of switches for each program even more confusing by interleaving completely unrelated functionality.

Either way, I suspect that you would be the only user of this functionality. I wouldn't use it myself.

Hence, if you want this functionality then I suggest you fork this repository and add it yourself.
