### ISSUE TITLE
Cant hide the switches from the dryer

### ISSUE THREAD

**Issue by renenm** [thoukydides/homebridge-homeconnect#25]
#### Description of Issue
In homebridge I selected "Program Switches" to "No individual program switches", but still it does show all the programms. The same setting is selected for the dishwasher and it works perfectly, only shows "on" and "off".

#### Plugin Version
v0.17.2

#### Home Connect Appliance(s)
Bosch Dryer (E-Nr: WTX87M40/01)

#### HomeKit App(s)
Apple Home

#### Log File
There is no specific log file, because it only affects the switch-states and visibility. No errors are shown in the log.

**Comment by thoukydides** [comment]
This is almost certainly a problem with your `config.json` file. The plugin handles programs for all appliance types (except Hood appliances) using the same code. If it works for the dishwasher then there is no reason why it will not work the same for the dryer.

The most likely issue is that the appliance's `haid` has not been copied correctly. There is no fuzzy matching - it must have matching case, punctuation, and no trailing spaces.

Are you editing the `config.json` file by hand, using the [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x) graphical settings editor, or a mixture of both?

Please can you provide a copy of your `config.json` file (making sure that you remove the `clientid` and any other secrets) and the `.homebridge-homeconnect-v1.schema.json` file from the same directory? Feel free to email them to me if you are uncomfortable posting them here.

**Comment by thoukydides** [comment]
I am closing this due to the lack of feedback.
Presumably it was caused by an incorrectly configured `config.json` file.
