### ISSUE TITLE
No Programm config options

### ISSUE THREAD

**Issue by Tom2Drake** [thoukydides/homebridge-homeconnect#29]
#### Description of Issue

I'm missing the program option here. Is this an API issue? For hot milk I have an "amount" selection but not for any coffee program.

![image](https://user-images.githubusercontent.com/13260476/83947204-efd95a00-a815-11ea-812d-d1120ff65600.png)

#### Plugin Version

v0.18.1

#### Home Connect Appliance(s)

Siemens EQ9 plus connect TI9555X1DE/10

#### HomeKit App(s)
Home

**Comment by thoukydides** [comment]
This looks like a repeat of #17. However, you haven’t provided any information that could help me to diagnose the problem.

Presumably you did have additional options available previously?
Have you changed or upgraded anything recently?

My guess is that you restarted the homebridge instance, but for some reason it was not possible for the plugin to turn on the coffee maker and select each program to read its options at that time.

Please try:
1. Stop the homebridge instance.
2. Delete all cache files, except for the `94a08da1fecbb6e8b46990538c7b50b2` file (see https://github.com/thoukydides/homebridge-homeconnect/wiki/Files#plugin-persistent-cache).
3. Ensure that the coffee maker is idle and ready (e.g. water and coffee present).
4. Restart homebridge, preferably in debug mode (with the `-D` command line option).
5. Wait for the plugin to finish initialising and reading the program options.
6. Invoke the HomeKit **Identify** method.
7. Check whether all expected options are now available.

If you do now have all expected options then it was probably a transient problem with the Home Connect servers or you appliance.

If those options are still missing then please provide the log file for the above sequence.

**Comment by Tom2Drake** [comment]
Following the 7 steps solved the issue for me. Thanks again for your Support.

**Comment by thoukydides** [comment]
That's great news. Thank you @Tom2Drake for the update.
