### ISSUE TITLE
Neff oven API error when starting a program via Home app

### ISSUE THREAD

**Issue by u20p17** [thoukydides/homebridge-homeconnect#30]
#### Description of Issue
I have added my NEFF oven (Neff N90 BVT5868HMC ) via this plugin to homebridge and I see the different programs also in the Home app. I can also remote start the oven, but as soon as I choose one program (in the log file below for example 'Auftaustufe') I get an API error. It seems that  the Control scope has not been authorised results in the API error, but how can I authorise that?

#### Plugin Version
homebridge-homeconnect v0.18.1

#### Home Connect Appliance(s)
Neff N90 BVT5868HMC

#### HomeKit App(s)
Apple Home + EVE

#### Log File
[2020-7-4 22:04:17] [HomeConnect] [Backofen] SET On
[2020-7-4 22:04:20] [HomeConnect] [Backofen] On
[2020-7-4 22:04:34] [HomeConnect] [Backofen] START Program 'Auftaustufe' (Cooking.Oven.Program.HeatingMode.Defrost)
[2020-7-4 22:04:34] [HomeConnect] [Backofen] Control scope has not been authorised
[2020-7-4 22:04:34] [HomeConnect] [Backofen] START active program Cooking.Oven.Program.HeatingMode.Defrost
[2020-7-4 22:04:45] [HomeConnect] [Backofen] START Program 'Auftaustufe' (Cooking.Oven.Program.HeatingMode.Defrost)
[2020-7-4 22:04:45] [HomeConnect] [Backofen] Control scope has not been authorised
[2020-7-4 22:04:45] [HomeConnect] [Backofen] START active program Cooking.Oven.Program.HeatingMode.Defrost
[2020-7-4 22:04:48] [HomeConnect] [Backofen] SET Off
[2020-7-4 22:04:48] [HomeConnect] [Backofen] Home Connect API error: HomeAppliance reported an error [BSH.Common.Error.WriteRequest.NotAvailableByList]
[2020-7-4 22:04:48] [HomeConnect] [Backofen] SET BSH.Common.Setting.PowerState=BSH.Common.EnumType.PowerState.Off
[2020-7-4 22:04:48] [HomeConnect] [Backofen] PUT https://api.home-connect.com/api/homeappliances/NEFF-B58VT68H0-68A40E30CBC7/settings/BSH.Common.Setting.PowerState
[2020-7-4 22:06:53] [HomeConnect] [Backofen] Inactive (Ready)

**Comment by thoukydides** [comment]
> I have added my NEFF oven (Neff N90 BVT5868HMC ) via this plugin to homebridge and I see the different programs also in the Home app. I can also remote start the oven, but as soon as I choose one program (in the log file below for example 'Auftaustufe') I get an API error. It seems that the Control scope has not been authorised results in the API error, but how can I authorise that?

Sorry, you cannot. (At least not unless you signed up for the Home Connect Developer Program as a business and sign an additional Partner Agreement.)

This limitation is described in the project's [README.md](https://github.com/thoukydides/homebridge-homeconnect/blob/master/README.md):

> ## Appliance Support
> ### Cooking Appliances
>  * **Oven:**
>    * *(It is not possible to control Oven programs due to the [Oven-Control scope](https://github.com/thoukydides/homebridge-homeconnect/wiki/Scopes) not being authorised; use [IFTTT](https://github.com/thoukydides/homebridge-homeconnect/wiki/IFTTT) instead.)*

For more details see https://github.com/thoukydides/homebridge-homeconnect/wiki/Scopes.

**Comment by u20p17** [comment]
Hi,
where can I find further information regarding the additional Partner Agreement? I have already signed up for the Home Connect Developer Program.

Furthermore, why is it then working with the iOS Home Connect App? There I can turn on/off the NEFF ans also select the different programs.

Thank you!

**Comment by thoukydides** [comment]
> where can I find further information regarding the additional Partner Agreement?

Did you actually bother looking at the links I provided in my last response?

Quoting from the [Home Connect Developer Agreement](https://developer.home-connect.com/developer_agreement):
> Certain additional permissions to those specified at: https://developer.home-connect.com/docs/authorization/scope may be granted to Clients of selected Users upon an individual check by HC and upon agreement of a separate partner agreement between the Parties, which is based on this Agreement.

You would need to contact **Home Connect GmbH, Carl-Wery-Straße 34, 81739 Munich, Germany (“HC”)** to form that agreement. They have previously stated that they will **not** do this with individuals:
> agreement with Home Connect is for business users, due to legal limitations, and potential risk of not correct usage of Hob (...) or Oven.

There is no point pursuing this.

> I have already signed up for the Home Connect Developer Program.

Yes, as an individual, and without the additional partner agreement. Hence, you are subject to the same limitations as all other independent developers.

> Furthermore, why is it then working with the iOS Home Connect App? There I can turn on/off the NEFF ans also select the different programs.

That is the official Home Connect application. It is not subject to the restrictions imposed on individual developers. It does not even use the same public API that other developers have to use, so has access to functionality that is not generally available (even with the additional partner agreement).

There is no point complaining here. There is absolutely nothing that I can do about it.

**Comment by thoukydides** [comment]
According to the [Home Connect changelog](https://developer.home-connect.com/changelog), the ability to authorise the `Oven-Control` scope was added on 31st March 2021.

Version 0.20.0 (and later) of this plugin requests `Control` scope for all appliance types, so is now able to start and stop Oven programs. In order to add the required scope it is necessary to re-authorise with the Home Connect API servers after upgrading the plugin. The easiest way to force this is by deleting the ` ~/.homebridge/homebridge-homeconnect/persist/94a08da1fecbb6e8b46990538c7b50b2` file while Homebridge is stopped.

**Comment by u20p17** [comment]
works perfekt - thanks! 👌
