### ISSUE TITLE
Buttons in HomeKit?

### ISSUE THREAD

**Issue by uspino2** [thoukydides/homebridge-homeconnect#31]
For every one of my appliances (Hood, Dishwasher and Cooktop), I get 2 tiles: a switch (with the accessories inside that I can show as separate tiles) and a button (that is also inside the switch). All buttons have unconfigured actions (1 for the hood, 2 for the dishwasher, 3 for the cooktop). I don't get what these are for...? If I just want an on/off switch + light control for each appliance, can I hide them all?

Thanks!

**Comment by thoukydides** [comment]
Have you tried looking at the documentation?

From the [README](https://github.com/thoukydides/homebridge-homeconnect/blob/master/README.md):
> * **Hood:**
>    * Automation trigger for finished.
>  * **Dishwasher:**
>    * Automation triggers for finished and aborted.
>  * **Hob:**
>    * Automation triggers for finished, timer finished, and preheat finished.

and from the Wiki [HomeKit-Mapping](https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Mapping):
> ## `Stateless Programmable Switch` Services for Events
> 
> Most appliance types can generate events, e.g. indicating when a program has finished, when a Freezer/Refrigerator door has been left open, or when a CoffeeMaker drip tray is full. This plugin creates a `Stateless Programmable Switch` service for each possible event (plus a single `Service Label` service) so that they can be used to trigger HomeKit automations.
> 
> Apple's Home app only shows numeric labels for these services instead of their names. This makes it difficult to construct HomeKit automations from these triggers. See the recommended [HomeKit Apps](https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Apps) that should be used instead.

Some of the better HomeKit apps (such as Matthias Hochgatterer's [Home+](http://hochgatterer.me/home/)) allow you to customise which services and characteristics are displayed. If you aren’t using one of those then you would need to modify this plugin if you don’t want those services to appear.

**Comment by thoukydides** [comment]
[v0.32.0](https://github.com/thoukydides/homebridge-homeconnect/releases/tag/v0.32.0) provides per-appliance configuration options to remove the `Stateless Programmable Switch` services for appliance events (as well as selectively enabling the `Switch` services for appliance mode settings and the `Door` services for the appliance door status).
