### ISSUE TITLE
Automation improvement

### ISSUE THREAD

**Issue by Kroellie** [thoukydides/homebridge-homeconnect#33]
When you have multiple devices, like I have, and you want to automate things at a certain time for example, you see multiple power toggles, but you're unable to determine which toggle is which device. Maybe there is an easy solution to this, but as far as I can see there isn't, other than error guessing.

**Comment by thoukydides** [comment]
This is a problem with the Apple Home app. There is nothing that this plugin can do to improve it. Sorry.

See [HomeKit Apps](https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Apps) for suggested alternatives.
