### ISSUE TITLE
CoffeeMaker auto standby not detected (Siemens TI9575X1DE/10)

### ISSUE THREAD

**Issue by zufivan** [thoukydides/homebridge-homeconnect#35]
#### Description of Issue
Hi, first thank you for your job, good integration. 

If I switch on and off by app the coffe machine is working fine, also by app Homeconnect.

**Problem description:**
after 1 hour onot working program the coffe machineare goiing itself to standby, The floow to power standby coffe machine:
inactive until 1 hour => clean the machine=> power standby

#### Home Connect Appliance(s)
Siemens CoffeeMaker (E-Nr: TI9575X1DE/10)

#### Log File
[2020-10-23 16:31:12] [HomeConnect] [Macchina Caffè] Active (Run)
[2020-10-23 16:31:12] [HomeConnect] [Macchina Caffè] Selected program null is not supported by the Home Connect API
[2020-10-23 16:31:49] [HomeConnect] [Macchina Caffè] Inactive (Inactive)

Thanks a lot for your cooperation.
Ivan

**Comment by thoukydides** [comment]
Please can you clarify what is actually going wrong? Unless I am missing it in your description, I cannot see an actual problem...

If it is just the "Selected program null" message in the log then I have submitted (but not released) a fix for that. It is just a cosmetic issue in the log that does not affect any actual HomeKit or Home Connect functionality.

**Comment by zufivan** [comment]
Sorry,  I forgot the most importat think, 
The Power button on the integration remaining switched on.. doesn't change to off. 

Thanks Ivan

**Comment by thoukydides** [comment]
Yes, that makes a difference!

Please can you provide a more complete log, captured with Homebridge debug enabled (using its `-D` command line switch).

I don't have access to a Home Connect coffee maker, and none of my appliances exhibit this behaviour. Hence, without more information there isn't anything that I can do to try and improve the plugin's behaviour.

**Comment by thoukydides** [comment]
There is a clear similarity between this issue and #32. Both are failures of the Home Connect API to correctly indicate changes in the appliance's `PowerState`... and they both occur with the same model of coffee maker.

The difference is that the previous issue related to the appliance switching on, for which the workaround was infer from `OperationState` changing to `Ready` that the power was switched on.

Hopefully something similar can be done for the appliance switching off, but I will need to view the debug log to see whether that it is the case...

**Comment by zufivan** [comment]
Hi thanks for your support,

See in attached 2 test with debug log,  one with 5 minute auto standby and the second with 1 hour auto standby.

Detail:
debug_auto standby_5 min.txt: (with 5 minutes auto standby is working fine)
Switch on machine => 14:32
Active program “Warm Milk” => 14:33
Auto power standby => 14:39

debug_auto standby_1 hour.txt: (with 1 hour auto standby is not working)
Switch on machine => 14:44
Active program “Warm Milk => 14:45
Auto power standby => 15:45
I don't khonw if there is some timeout or time pooling.. tomorrow I will try with auto standby 30 minute, maiybe can help you..
Many thanks Ivan

[debug_auto standby_5 min.txt](https://github.com/thoukydides/homebridge-homeconnect/files/5433322/debug_auto.standby_5.min.txt)
[debug_auto standby_1 hour.txt](https://github.com/thoukydides/homebridge-homeconnect/files/5433323/debug_auto.standby_1.hour.txt)

**Comment by thoukydides** [comment]
Thank you @zufivan for those logs. They tell me everything that I need. Don't waste your time collecting logs with other timeout values - they won't provide any additional useful information.

It looks like the only available trigger for detecting that the appliance has switched off is `BSH.Common.Status.OperationState` being set to `BSH.Common.EnumType.OperationState.Inactive`. (There are some others generated around the time of the switch off, but they either also occur whilst the appliance is active, or like the `ApplianceOffRinsing` program occur up to a minute before the actual switch off which makes them tricky to use safely.)

Unfortunately, `BSH.Common.EnumType.OperationState.Inactive` is reported for both the `BSH.Common.EnumType.PowerState.Off` and `BSH.Common.EnumType.PowerState.Standby` states. I need to review my code carefully to check whether anything actually cares about the distinction between those states. It is possible that I may get away with just treating `Inactive` whilst `On`  as an indication of going to `Standby`, and a subsequent event might then change it to `Off` for appliances that support that state.

If that simple workaround isn't feasible, then my backup strategy is to use the `Inactive` event to trigger a poll of the `PowerState`. That sounds like the safer option... except that I have seen logs from appliances that don't always allow the `PowerState` to be read, and it increases the likelihood of hitting the Home Connect API rate limits. Hence, why I would prefer to avoid this approach.

I will take another look tomorrow...

**Comment by thoukydides** [comment]
OK, following a quick code review... the plugin only checks whether the `PowerState` is `On` or not, so doesn't distinguish between `Off` or `Standby` (at least not for events - it only cares when trying to set those states). Hence, the simpler workaround should be viable.

I will implement something tomorrow for you to try...

**Comment by thoukydides** [comment]
I have just released v0.18.3 which should address this issue.

**Comment by zufivan** [comment]
Hi @thoukydides  NOw is working perfect, 
Thanks a lot for your great support and the good integration.

**Comment by thoukydides** [comment]
Thank you @zufivan for testing this and providing feedback quickly.
