### ISSUE TITLE
Oven door switch

### ISSUE THREAD

**Issue by noppie** [thoukydides/homebridge-homeconnect#36]
#### Description of Enhancement
Is it possible to add an option to monitor the oven door wether it's open or closed?

#### Home Connect Appliance(s)
Siemens Oven (E-Nr: HM836GNB6/53)

**Comment by thoukydides** [comment]
That is already fully supported. Try reading the documentation:
* https://github.com/thoukydides/homebridge-homeconnect/wiki/Functionality
* https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Mapping

This is how it appears in Matthias Hochgatterer's [Home+](http://hochgatterer.me/home/) app:
![image](https://user-images.githubusercontent.com/4775242/97160226-ed9b7c00-1773-11eb-8435-86c6e6a45a31.jpeg)
![image](https://user-images.githubusercontent.com/4775242/97160232-f12f0300-1773-11eb-82d5-58b10bd8ab9b.jpeg)

**Comment by noppie** [comment]
Sorry, let me ask another question:  Is it possible to monitor in Apple Homekit wether the oven door is open or closed?

**Comment by thoukydides** [comment]
It depends what you mean by "monitor in Apple HomeKit".

It is provided as a HomeKit characteristic that can be viewed in HomeKit apps (but not Apple's own Home app) and can be used to trigger HomeKit automations. You have to use a third-party HomeKit app to see it; I highly recommend Matthias Hochgatterer's [Home+](http://hochgatterer.me/home/) app.

I will not be modifying the plugin to use a HomeKit service that is displayed by Apple's Home app. I already receive far too many complaints from other users about the number of services that the plugin creates.

**Comment by noppie** [comment]
Thanks for the reply and your good work.   I use Homebridge  but don't see the Oven Door in my accessories......

**Comment by thoukydides** [comment]
Like I said, it won't appear in Apple's Home app. You need to use a third-party HomeKit app.

If you don't want to spend money on Home+, then Eglato's [Eve](https://www.evehome.com/en/eve-app) app is another good choice. That also shows the oven door status.

**Comment by noppie** [comment]
Ah,  I understand.  Thank you for the reply
