### ISSUE TITLE
config within HOOBS and identify in eve

### ISSUE THREAD

**Issue by emufan** [thoukydides/homebridge-homeconnect#37]
At first: Great connector. Great description. Thx so much.

Currently I face some problems but want to dig into this on my own.

But in the documentation you are referring to HOOBS and that the configuration there has to be done via .homebridge-homeconnect-v1.schema.json, etc. But I'm unable to find this within my HOOBS docker. Do you have an idea/hint, where this is stored?

And you recommend to initiate identify in other apps like eve. But who to trigger this there? I cannot find a button or routine there. Do you have an idea or hint as well?

Thanks and best regards

**Comment by thoukydides** [comment]
> But in the documentation you are referring to HOOBS and that the configuration there has to be done via .homebridge-homeconnect-v1.schema.json, etc. But I'm unable to find this within my HOOBS docker. Do you have an idea/hint, where this is stored?

I think you have misunderstood.

This plugin generates the `.homebridge-homeconnect-v1.schema.json` file to describe its configuration file format. You should never edit or attempt to parse that file by hand. It is solely to control the GUI presented by [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x) for editing the plugin's configuration. It is of absolutely no relevance if you are using HOOBS.

I do not use HOOBS, so cannot advise on how to use this plugin with it. However, I would expect it to provide a way to edit the plugin's `config.json` file by hand; probably under the plugin's **Advanced** settings.

> And you recommend to initiate identify in other apps like eve. But who to trigger this there? I cannot find a button or routine there. Do you have an idea or hint as well?

In Eve, select the Rooms tab, find one of the appliances added by this plugin, and click on its name (not any of the active controls). This will open a more detailed screen showing all of the appliance's services and characteristics. At the top of the screen, under the back and edit buttons, it will have the appliance's name and an arrow pointing right. Click on that name/arrow and two more buttons will appear: a cog and an ID button. The ID button triggers the Identify mechanism.

**Comment by emufan** [comment]
More than great. Thanks for the explanation. Now this is clear and is working as you described.
