### ISSUE TITLE
Siemens EQ.500 integral: no hot water program

### ISSUE THREAD

**Issue by boehser-enkel** [thoukydides/homebridge-homeconnect#44]
#### Description of Issue
Every program is shown in Home except Hot Water function (and coffee jug, but i don't need this for now)

#### Plugin Version
0.19.0

#### Home Connect Appliance(s)
Siemens EQ.500 integral
TQ507DF3/03

#### HomeKit App(s)
Any

#### Log File
No log relevant?

kind regards
boehser enkel

**Comment by thoukydides** [comment]
This is a limitation of the Home Connect API. It does not support all appliance capabilities. This plugin cannot provide functionality that is not supported by the Home Connect API.

You can check the list of supported CoffeeMaker programs here:
https://developer.home-connect.com/docs/coffee-maker/supported_programs_and_options

Feel free to request this functionality - it is more likely to be added if more people request it:
https://developer.home-connect.com/support/contact
