### ISSUE TITLE
Contact Sensor (how does the coffee maker switch work?)

### ISSUE THREAD

**Issue by boehser-enkel** [thoukydides/homebridge-homeconnect#45]
#### Description of Enhancement
Hey,
can you include a contact sensor instead of a switch that is triggered (for coffee maker  "water empty, "drip tray full", "ban container empty")
How does this switch even work? Is it "pressed" every time the coffee maker is turned on, or just when the status occurs?

#### Home Connect Appliance(s)
Coffee Maker

**Comment by thoukydides** [comment]
No, that is not possible. The CoffeeMaker only reports events for changes to the state of the bean container, water tank, drip tray etc. It is not possible to determine the current state when the plugin is started or when a connection to the appliance is established. See https://developer.home-connect.com/docs/monitoring/appliance_events for details of these events.

Hence, the plugin just converts those Home Connect events into instantaneous presses of the Stateless Programmable Switch. This can be used to trigger automations.

**Comment by boehser-enkel** [comment]
No i did not want the current state of these 3. Instead i wanted a notification u can use in home when there is a contact sensor. It could open and close instantly when the event occurs.

**Comment by thoukydides** [comment]
That is already supported via the existing Stateless Programmable Switch. I cannot see any benefit to replacing that by a Contact Sensor. 

The Contact Sensor service uses a Contact Sensor State characteristic, which the HAP specificiation describes as:
> This characteristic describes the state of a door/window contact sensor. A value of 0 indicates that the contact is
detected. A value of 1 indicates that the contact is not detected.

In this application it would not be indicating the status of a door or window, and it would not be indicating a continuous state. Hence, it would be an inappropriate service/characteristic for this purpose. The existing Stateless Programmable Switch is more appropriate.

I do not own or have access to a Home Connect CoffeeMaker so I cannot properly test any functionality specific to those appliances.  Hence, I am not willing to make changes for those appliances without good reason.

**Comment by boehser-enkel** [comment]
Okay but it just would be easier because a switch does not trigger a notification within home (at least not without a few exra steps)
