### ISSUE TITLE
Which coffe options with automatic buttons

### ISSUE THREAD

**Issue by boehser-enkel** [thoukydides/homebridge-homeconnect#46]
Hey,
which coffee options (strength, ml) are used when i let the plugin create the buttons automatically.
Are the default options used or the last set options?

kind regards

**Comment by thoukydides** [comment]
If you don't configure any options for starting a program then this plugin does not specify any options to the Home Connect API.  The Home Connect servers or appliance will then pick values for those options itself; presumably either a default for that program or the last used setting. I would expect it to behave similarly to selecting the program manually on the appliance without changing any options.

See https://github.com/thoukydides/homebridge-homeconnect/wiki/Programs for an explanation of how to configure program options. This is easiest to do via the [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x) GUI.

If you use the Homebridge Identify method on the appliance then the debug log will show the default values for each program option.
