### ISSUE TITLE
See remaining time in homekit?

### ISSUE THREAD

**Issue by sjaccoo2001** [thoukydides/homebridge-homeconnect#48]
Is there any way to see the remaining time of my washer and dryer in homekit?

**Comment by thoukydides** [comment]
Yes. It is available as the `RemainingTime` characteristic on the main Active Program `Switch` service. See https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Mapping#extra-active-program-switch-characteristics.

This characteristic is not visible within Apple's Home app, so you will need to use a third-party app to view it or to use it to trigger an automation. See https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Apps.

**Comment by nixmeer** [comment]
I got a question regarding the topic: I use the [homebridge-mqttthing](https://github.com/arachnetech/homebridge-mqttthing) plugin for sprinklers and they show the remaining time in the middle of the sprinkler switch. Does Apple prevent this for other device types? Or is there another issue why it's not visible in a "relay" switch?

**Comment by thoukydides** [comment]
Apple's Home app generally only supports characteristics that are defined as being either Required or Optional in the HAP Specification. For the Remaining Duration that is just the Irrigation System and Valve accessories. Neither of those are suitable for the appliances supported by this plugin.

Some third-party HomeKit apps do show the Remaining Duration for other accessory types, including this plugin's.

**Comment by nixmeer** [comment]
> Some third-party HomeKit apps do show the Remaining Duration for other accessory types, including this plugin's.
I know, I've read the that in the documentation. 

> For the Remaining Duration that is just the Irrigation System and Valve accessories. Neither of those are suitable for the appliances supported by this plugin.
First part is simply sad. HomeKit and the app could be so much more powerful. Second part is true. 

Thanks for the info!
