### ISSUE TITLE
Too many switches

### ISSUE THREAD

**Issue by tomeranaray** [thoukydides/homebridge-homeconnect#49]
I have a Siemens washer and dryer, and when exposing them in HomeKit, I end up with over 20 new switches for various cycles. As they are all non-functional when the devices are off, and also when the machines are running, they’re quite useless, confusing and cluttering up the HomeKit interface. 

Would it be possible to add an option to hide the program cycles? I would be more than happy with just the timer, the current state and a switch for on/off or play/pause in HomeKit.

**Comment by tomeranaray** [comment]
Sorry, I just found the solution: https://github.com/thoukydides/homebridge-homeconnect/wiki/Programs

**Comment by thoukydides** [comment]
If you use [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x) to edit the plugin’s configuration (which is highly recommended) then just select the `No individual program switches` option.
