### ISSUE TITLE
Issues with registering an application on HomeConnect

### ISSUE THREAD

**Issue by cyrilleroux** [thoukydides/homebridge-homeconnect#51]
#### Description of Issue
Context: I've been using HomeConnect with a dishwasher for a few days now. I'm now trying to add it to my HomeKit setup.

I'm on step 2)ii of the installation instructions. Under "Register Application", I don't know what to use for Application ID and Redirect URI. These mandatory fields are not mentioned in the instructions.
![Screenshot 2021-03-15 at 15 03 59](https://user-images.githubusercontent.com/5576573/111175298-32e40d00-85a0-11eb-8a66-61adc82a7541.png)

I've noticed that there **already** was an API Web Client ID on my account. But this one doesn't work, presumably due to the oAuth Flow not being set to Device Flow.

![Screenshot 2021-03-15 at 15 08 06](https://user-images.githubusercontent.com/5576573/111176582-5eb3c280-85a1-11eb-8eb4-e25e3f43135a.png)

#### Plugin Version
v0.19.2

#### Home Connect Appliance(s)
Bosch Dishwasher SPV4EMX21G/02

#### Log File
```[15/03/2021, 14:35:43] [HomeConnect] No saved authorisation data found
[15/03/2021, 14:35:43] [HomeConnect] Requesting Home Connect authorisation using the Device Flow
[15/03/2021, 14:35:43] [HomeConnect] Home Connect API error: Unable to authorise Home Connect application; client not authorized for this oauth flow (grant_type). Visit https://developer.home-connect.com/applications to register a new application, ensuring that the 'OAuth Flow' is set to 'Device Flow' (this setting cannot be changed after the application has been created).
[15/03/2021, 14:35:43] [HomeConnect] Retrying client authentication in 60 seconds
```

**Comment by thoukydides** [comment]
Change the "OAuth Flow" to "Device Flow".

The Application ID is just a friendly name that you can set to anything you like.
Similarly, the Success Redirect can be set to any URL you like.
Neither of these affect the authorisation process, which is why the instructions don't specify particular values.

The API Web Client ID is for the web-base API client at https://apiclient.home-connect.com/ only. It is not for general use.

**Comment by cyrilleroux** [comment]
All working now. Thanks a lot!
