### ISSUE TITLE
Apple Home App Favorites View

### ISSUE THREAD

**Issue by Nastras** [thoukydides/homebridge-homeconnect#52]
Hello @thoukydides,
today the behavior I told you yesterday in the smart apple forum occurred again. Both Home Connect devices reappeared as if by magic on the Favorites page of the Apple Home app. I have looked in the journalctl. But could not discover anything unusual here. It does not look to me that the devices were newly added to Homekit. Neither of my devices were turned on or connected to wifi today. When I call the journalctl now it still looks exactly like on the screen.
![F4081002-2D99-424A-9969-1CAAB9F31488](https://user-images.githubusercontent.com/27686185/111509566-24872400-874d-11eb-8f70-0d42aade5204.jpeg)

![8E53DD58-51D8-4BBB-9FC7-35DA8AD16410](https://user-images.githubusercontent.com/27686185/111509735-51d3d200-874d-11eb-858f-9d829db3ae9d.jpeg)

Would be great if you can look through the journalctl if something seems suspicious to you.

Thank You!

Regards
Nastra

**Comment by thoukydides** [comment]
You have not provided any particularly useful information here.

The tiny excerpt from the log just shows that neither appliance is currently accessible by the Home Connect servers, which matches you saying that they were not switched on. If the appliances are registered to your account then I would expect them to remain visible in HomeKit, which matches your screenshot.

This plugin only adds or removes accessories from HomeKit if the Home Connect API adds or removes them from the list of appliances that it knows about. The portion of the log that you provided does not show this happening, which is normal even if the appliances cannot currently be reached. However without homebridge debug logging enabled the log does not reveal whether the Home Connect API actually returned any list of appliances.

All of the information that you have provided just shows everything working correctly and as expected. Given how badly the Home Connect API has been behaving over the last couple of days that is quite surprising.

If you want me to look at this further then:
1. Wait for the Home Connect servers to be operating reliably as indicated by https://www.thouky.co.uk/homeconnect.html
2. Run homebridge with debug logging enabled (using the `-D` command line switch).
3. Wait for behaviour that you consider to be incorrect.
4. Provide a full copy of the log as text (not a screenshot), without redaction.
5. Provide a clear description of what exactly didn’t behave how you expected, with the approximate date/time of that event.

**Comment by Nastras** [comment]
I am aware that the information I have given you is not very deep yet. But I don't have much more information at the moment. I'm sorry. I wanted to follow up with you. 

Problem with the whole thing is that I can't identify the time when the devices suddenly reappear in the home app on the favorites page.

The devices disappear after an undefined time on their own. Maybe it is also a bug of the home app. Whereby the behavior only occurs with Home Connect devices.

I will turn on the debug mode now and hope that I can provide more information in the days.

Thanks!

**Comment by Nastras** [comment]
Hello @thoukydides,

since the error has not yet reappeared and it sometimes takes a long time until it appears again, I close the issue for now.

I still leave the debug mode on. As soon as I have detailed information I will report here again.

**Comment by Nastras** [comment]
Hello @thoukydides,
I wanted to get back to you about the problem. I completely removed my homebridge instance for your plugin after we wrote last time from HomeKit and added it again. As well as deleted the cache files. Since then, the error no longer occurs.

So everything is great. Thanks!

**Comment by thoukydides** [comment]
That's great. Thanks for letting me know.
