### ISSUE TITLE
npm ERR! ENOTEMPTY: directory not empty

### ISSUE THREAD

**Issue by DJay-X** [thoukydides/homebridge-homeconnect#53]
[2021-05-01T17_14_10_392Z-debug.log](https://github.com/thoukydides/homebridge-homeconnect/files/6410028/2021-05-01T17_14_10_392Z-debug.log)
#### Description of Issue

Trying to install the latest version 0.22.0 is bringing the error in the log. 
I the plugin on the 2nd-Instance but in the past never had any issues with this.

#### Plugin Version

Back to 0.21.0 everything is working as expected.

#### Home Connect Appliance(s)

BOSCH-CTL636ES6 Coffee Maker

#### HomeKit App(s)

Node.js Version | v14.16.1
npm v7.11.2
homebridge-config-ui-x v4.41.1
Homebridge 1.3.4

#### Log File

```
USER: homebridge
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-homeconnect@latest

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-homeconnect
npm ERR! dest /usr/local/lib/node_modules/.homebridge-homeconnect-kZrQpYS9
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-homeconnect' -> '/usr/local/lib/node_modules/.homebridge-homeconnect-kZrQpYS9'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2021-05-01T17_14_10_392Z-debug.log

Command failed. Please review log for details.
[2021-05-01T17_14_10_392Z-debug.log](https://github.com/thoukydides/homebridge-homeconnect/files/6410018/2021-05-01T17_14_10_392Z-debug.log)

```

**Comment by thoukydides** [comment]
It installs fine for me:
```
> npm -g install homebridge-homeconnect
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142

added 63 packages, and audited 64 packages in 5s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

I have not changed anything related to how this plugin is packaged.

Hence, I suggest that you delete the `/usr/local/lib/node_modules/.homebridge-homeconnect-kZrQpYS9` directory and try again.

**Comment by DJay-X** [comment]
Thanks.
And strange. I run the update again by config UI as before but now everything was running and installing as expected. 
Anyways, thanks for the quick check.
I hope you are well and safe. 
I'm always happy to see ongoing work with this plugin. Thanks a lot.
Cheers 👍
