### ISSUE TITLE
Is it possible to disable certain appliances from the plugin settings? 

### ISSUE THREAD

**Issue by siqiha** [thoukydides/homebridge-homeconnect#57]
I only want to expose one appliance to HomeKit, but I cannot find a way is to hide or disable them. If there are other methods, please let me know. Thanks.

**Comment by thoukydides** [comment]
No, that is not supported.

You can stop Switch services being added for particular appliances, but you cannot stop the basic services like the power Switch from being created.

**Comment by siqiha** [comment]
I would be nice to have this feature. I only want to enable the hood in the HomeKit(Turn on Hood when Co2 is high), not washing machine, dryer etc, since too many unused accessories in HomeKit is not so convenient.

**Comment by thoukydides** [comment]
I understand why you would like this extra configurability. However, I am unlikely to implement it any time soon, if at all.

Most of the reasons that I gave for not implementing #56 also apply to this.

**Comment by thoukydides** [comment]
Added in [v0.37.0](https://github.com/thoukydides/homebridge-homeconnect/releases/tag/v0.37.0).
