### ISSUE TITLE
Installing the plugin on the new Raspbian Bullseye

### ISSUE THREAD

**Issue by JornDL** [thoukydides/homebridge-homeconnect#65]
#### Description of Enhancement

Installing the plugin on the new Raspbian Bullseye

**Comment by thoukydides** [comment]
You will need to provide far more information than that if you expect any assistance.

Do you have homebridge working with other plugins?
Are you trying to install the plugin by hand editing the config.json file or using the homebridge-config-ui-x GUI?
What doesn’t work?
Are there any errors or log files?

**Comment by JornDL** [comment]
Hi

Sorry about that.

I have a running Homebridge Buster installation with among others this plugin.

So I just wanted to know if this plugin should be running fine also on a Homebridge BullsEye installation, before I jump in and do an upgrade.

BR Jørn Dalgård Larsen

Fra: Alexander Thoukydides ***@***.***>
Svar til: thoukydides/homebridge-homeconnect ***@***.***>
Dato: lørdag den 13. november 2021 kl. 11.47
Til: thoukydides/homebridge-homeconnect ***@***.***>
Cc: JornDL ***@***.***>, Author ***@***.***>
Emne: Re: [thoukydides/homebridge-homeconnect] Installing the plugin on the new Raspbian Bullseye (Issue #65)


You will need to provide far more information than that if you expect any assistance.

Do you have homebridge working with other plugins?
Are you trying to install the plugin by hand editing the config.json file or using the homebridge-config-ui-x GUI?
What doesn’t work?
Are there any errors or log files?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthoukydides%2Fhomebridge-homeconnect%2Fissues%2F65%23issuecomment-968048165&data=04%7C01%7C%7Cc9e06c27a5bb4b56a9be08d9a692f35c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723972340571121%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AUE2l6%2BaeCk5BGQmz%2BZoJsBYmR56HQMk%2BZAkl6FK4Wk%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT6A367HZOYIEP265PZH3K3ULY627ANCNFSM5H6KOTLQ&data=04%7C01%7C%7Cc9e06c27a5bb4b56a9be08d9a692f35c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723972340581075%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kKip56UvkXV%2FJfvkJfXGByQGBa2p1HJOzu0Pvq6UfwI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc9e06c27a5bb4b56a9be08d9a692f35c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723972340581075%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1IhMtk3%2FNshwTn6DmMIenrjk%2Brt7aQmpBoiY8xgLzZE%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cc9e06c27a5bb4b56a9be08d9a692f35c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723972340591036%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IVJqBA4AsA4SXuMIy9W729GW0C8xvSpStk5BPkKjqN8%3D&reserved=0>.

**Comment by thoukydides** [comment]
This plugin does not have any external dependencies beyond homebridge and Node.js. If Bullseye has a different version of Node.js than Buster then there is a small risk that it might break something, requiring an update to this plugin. That is quite unlikely though.

I do not run homebridge on a Raspberry Pi myself so cannot tell you whether it will work. Sorry.

If you do find that something breaks then raise another issue with full details and I will try to fix it quickly.

**Comment by JornDL** [comment]
Hi

Thanks a lot for you answer.

BR Jørn Dalgård Larsen

Fra: Alexander Thoukydides ***@***.***>
Svar til: thoukydides/homebridge-homeconnect ***@***.***>
Dato: lørdag den 13. november 2021 kl. 12.43
Til: thoukydides/homebridge-homeconnect ***@***.***>
Cc: JornDL ***@***.***>, Author ***@***.***>
Emne: Re: [thoukydides/homebridge-homeconnect] Installing the plugin on the new Raspbian Bullseye (Issue #65)


This plugin does not have any external dependencies beyond homebridge and Node.js. If Bullseye has a different version of Node.js than Buster then there is a small risk that it might break something, requiring an update to this plugin. That is quite unlikely though.

I do not run homebridge on a Raspberry Pi myself so cannot tell you whether it will work. Sorry.

If you do find that something breaks then raise another issue with full details and I will try to fix it quickly.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthoukydides%2Fhomebridge-homeconnect%2Fissues%2F65%23issuecomment-968055229&data=04%7C01%7C%7C20fb8a9610e942022a5d08d9a69ac984%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637724005992944723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g6N9w%2BpISk7aFq3d5BE8l%2FeauzktKB5Bq%2FMK6Ce3QZM%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT6A366KFVRC4MVEEH3HCQLULZFNJANCNFSM5H6KOTLQ&data=04%7C01%7C%7C20fb8a9610e942022a5d08d9a69ac984%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637724005992944723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pax%2BmzJVohGlzu9TdDe%2BwnVX%2FyrqFBjbr%2FA4azQOT9k%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C20fb8a9610e942022a5d08d9a69ac984%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637724005992954679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Z9lg%2BSAXvSXrcuFhTVCR1DfPN7hhtewOmVKPCOnhPOk%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C20fb8a9610e942022a5d08d9a69ac984%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637724005992954679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rVtASQOwDanPkcA5NSWGUEJdPFpaApXxWHNsTfZv7ds%3D&reserved=0>.
