### ISSUE TITLE
Plugin triggers Button on reconnect

### ISSUE THREAD

**Issue by clickme83** [thoukydides/homebridge-homeconnect#66]
While reconnecting to the cloud the button "Program finished" is triggered.

Version: homebridge-homeconnect v0.23.3

Appliance: Bosh Dishwasher SMV4HVX31E/26

#### HomeKit App(s)

```
[12/9/2021, 12:23:10 AM] [HomeConnect] [Dishwasher] Disconnected
[12/9/2021, 12:23:16 AM] [HomeConnect] [Dishwasher] Door closed
[12/9/2021, 12:23:16 AM] [HomeConnect] [Dishwasher] Inactive (Inactive)
[12/9/2021, 12:23:16 AM] [HomeConnect] [Dishwasher] Remote operation enabled (remote control activated, remote start allowed)
[12/9/2021, 12:23:16 AM] [HomeConnect] [Dishwasher] Event Program Finished
[12/9/2021, 12:23:16 AM] [HomeConnect] [Dishwasher] Off
[12/9/2021, 12:23:16 AM] [HomeConnect] [Dishwasher] Connected
```

**Comment by thoukydides** [comment]
Checking the log files for my own instance of this plugin, with a Siemens iQ700 Dishwasher (SN678D06TG/53), the `Program Finished` single press event is not triggered when a connection is re-established.

This plugin only triggers `ProgrammableSwitchEvent` characteristics when it receives the corresponding event from the Home Connect servers. The `Event Program Finished` log entry that you quote requires the event `BSH.Common.Event.ProgramFinished = BSH.Common.EnumType.EventPresentState.Present` to have been received.

It would be helpful if you could provide a more complete log with debug enabled (by launching homebridge with the `-D` command line option). If this is indeed being reported as an event by the Home Connect appliance/servers then it should look something like:
```
[HomeConnect] [Dishwasher] Event EVENT (1 item)
[HomeConnect] [Dishwasher] BSH.Common.Event.ProgramFinished=BSH.Common.EnumType.EventPresentState.Present (2 listeners)
[HomeConnect] [Dishwasher] Event Program Finished
```

I suspect that this is just a quirk of the Bosch Dishwasher SMV4HVX31E/26. If so, the only thing I can do is report it to the Home Connect team. This plugin does not do any processing or filtering of events; they are mapped directly to the HomeKit triggers.

**Comment by clickme83** [comment]
I just started homebridge with -D in a screen session. I come back when it happen again

**Comment by thoukydides** [comment]
It has been two months without any further report of problems, so I am going to close this issue. Feel free to re-open it if the problem recurs and you are able to provide a debug log.
