### ISSUE TITLE
Intellidry feature

### ISSUE THREAD

**Issue by darrenmcuk** [thoukydides/homebridge-homeconnect#75]
Hi,

We have a i700 washing machine and i700 dryer which come with the intellidry transfer option. Is there any way to support this feature in the plugin?

thanks.

**Comment by thoukydides** [comment]
If that feature can be supported then it already is. The plugin does not have any appliance program options hardcoded - the capabilities of each program are read from the Home Connect API.

Home Connect Dryers appliances generally support a subset of:
https://api-docs.home-connect.com/programs-and-options?#dryer

If the feature you want is not listed in that documentation, or is listed there but not supported by the appliance, then you could request its addition here:
https://developer.home-connect.com/support/contact

The Home Connect team maintain a wish list of requested functionality.
