### ISSUE TITLE
Failed to read list of home appliances: TypeError: Home Connect API error: AbortSignal.timeout is not a function

### ISSUE THREAD

**Issue by takenek** [thoukydides/homebridge-homeconnect#80]
Hello
After update to version 0.24 i get error:
Failed to read list of home appliances: TypeError: Home Connect API error: AbortSignal.timeout is not a function

Best Regards
TaKeN

**Comment by thoukydides** [comment]
It looks like that was added in Node 16.14.
I have updated the minimum required Node version in v0.24.1.

**Comment by takenek** [comment]
Ohh now i get:
The homebridge-homeconnect plugin should be installed using Node.js version 16.14.0 or later. You are currently using Node.js v16.13.2.

**Comment by takenek** [comment]
Doing hb-service update-node - we will see what happened ;-)

Now everything die... omg...

root@radvd:~# hb-service update-node
ℹ Updating Node.js from v16.13.2 to v16.14.2...
ℹ Target: /usr/local
✔ Download complete.
✔ Cleaned up npm at at /usr/local/lib/node_modules/npm
✔ Installed Node.js v16.14.2
ℹ Restarting Homebridge Service...
✔ Homebridge Restarted

and stop working.. reboot not help...

root@radvd:~# node
-bash: /usr/local/bin/node: no such file or directory

**Comment by thoukydides** [comment]
Sorry, I can't help you with that one.

I have never used `hb-service` (I always use `n` to update the installed version of node)... although I suspect that isn't the problem since it looks like you have a version of node installed.

**Comment by takenek** [comment]
OK i repair this problem with node and now version v0.24.1 now working good.
