### ISSUE TITLE
request rejected by client authorization authority

### ISSUE THREAD

**Issue by Radstake** [thoukydides/homebridge-homeconnect#82]
#### Description of Issue
Created an application, provide ID in the plugin, getting this error _request rejected by client authorization authority_

#### Plugin Version
v0.24.1

#### Log File

```
[4/11/2022, 3:16:46 PM] [HomeConnect] No saved authorisation data found
[4/11/2022, 3:16:46 PM] [HomeConnect] Requesting Home Connect authorisation using the Device Flow
[4/11/2022, 3:16:47 PM] [HomeConnect] Home Connect API error: Unable to authorise Home Connect application; request rejected by client authorization authority (developer portal). Visit https://developer.home-connect.com/applications to register an application and then copy its Client ID.
[4/11/2022, 3:16:47 PM] [HomeConnect] Retrying client authentication in 60 seconds
```

**Comment by floriangrotz** [comment]
No but, you have to open a link which is provided after the start - It authenticate the access on the used account where your appliances are stored. Reopen the settings - the link is also there visible. 
See Point 6 on the installation manual 
6. The Homebridge log output will include an authorisation URL. Copy the listed URL into a web browser and login to your Home Connect account. (The authorisation URL can also be found in the [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x) graphical settings editor.)

**Comment by thoukydides** [comment]
That error is generated by the Home Connect servers because you have not provided a valid application Client ID.

Ensure that you have copied the full 64-character hex string "Client ID" from the application that you created on the Home Connect site. (Not the one for the "API Web Client", and not the "Client Secret".)

**Comment by floriangrotz** [comment]
@thoukydides - thats not correct - the authorization data is created after putting the client ID in. 
You have to open the link, login into the account where the homeconnect devices are and grant access.

**Comment by thoukydides** [comment]
@floriangrotz I am the author of this plugin. I think I know what I am talking about!

The `Unable to authorise Home Connect application; request rejected by client authorization authority (developer portal).` error is returned by the Home Connect servers because it has not been provided with a valid Client ID. The servers will not have provided an authorization URL in this case. It is not getting as far as requesting authorization via the user's account.

**Comment by floriangrotz** [comment]
@thoukydides  Mea culpa - I´ve overread developer portal
Thanks for providing the plugin!

**Comment by thoukydides** [comment]
I have just tried creating a new application on the Home Connect Developer site and configuring a new Homebridge instance to use it, and it is working correctly. The log file shows:
```
[11/04/2022, 15:22:20] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge Dev) is running on port 51911.
[11/04/2022, 15:22:20] [HomeConnect] No saved authorisation data found
[11/04/2022, 15:22:20] [HomeConnect] Requesting Home Connect authorisation using the Device Flow
[11/04/2022, 15:22:20] [HomeConnect] Home Connect request #1: POST https://api.home-connect.com/security/oauth/device_authorization
[11/04/2022, 15:22:20] [HomeConnect] Home Connect request #1: OK +332ms
[11/04/2022, 15:22:20] [HomeConnect] Home Connect authorisation required. Please visit:
[11/04/2022, 15:22:20] [HomeConnect]     https://api.home-connect.com/security/oauth/device_verify?user_code=xxxx-xxxx
[11/04/2022, 15:22:20] [HomeConnect] Waiting for completion of Home Connect authorisation (poll every 5 seconds, device code xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx expires after 600 seconds)...
```

**Comment by Radstake** [comment]
- I installed the homebridge homeconnect plugin.
- Created a application in the dev portal.
- Copied the new CliendID in the config.
- Restarted homebridge
- No link, just the error:

[4/11/2022, 3:16:46 PM] [HomeConnect] No saved authorisation data found
[4/11/2022, 3:16:46 PM] [HomeConnect] Requesting Home Connect authorisation using the Device Flow
[4/11/2022, 3:16:47 PM] [HomeConnect] Home Connect API error: Unable to authorise Home Connect application; request rejected by client authorization authority (developer portal). Visit https://developer.home-connect.com/applications to register an application and then copy its Client ID.
[4/11/2022, 3:16:47 PM] [HomeConnect] Retrying client authentication in 60 seconds

**Comment by bpwiselybabu** [comment]
For those who are scratching their head I realized that I needed to set the

`Application ID *` as `homebridge-homeconnect` on the bosch developer site for this to work. Maybe this has to be added to the readme?

**Comment by Radstake** [comment]
Thx for the feedback.

As the ID is valid, tested it, and copied it correctly, it can be homeconnect issue. I’ll try again tomorrow.

**Comment by phyber** [comment]
There is probably some latency on the homeconnect side for the ClientID to become active, I've just experienced this same error for a while. I'm now stuck at the "SingleKey ID" login, a site I've never seen while signing up to the rest of this stuff and which rejects the email/password setup for home-connect.

**Comment by thoukydides** [comment]
> I'm now stuck at the "SingleKey ID" login, a site I've never seen while signing up to the rest of this stuff and which rejects the email/password setup for home-connect.

This might help: https://www.home-connect.com/gb/en/help-support/singlekey-id

I don't get a prompt to create or link a SingleKey ID within the Home Connect app so I am unable to test this.

When I authorise this plugin the website asks whether I want to use a Home Connect login or a Single Key ID. I am surprised that you don't get the same option.

**Comment by phyber** [comment]
> I am surprised that you don't get the same option.

It just goes directly to a singlekey-id.com login page.

> I don't get a prompt to create or link a SingleKey ID within the Home Connect app so I am unable to test this.

I never had this either. I just created a login in the HomeConnect app, created a developer account via https://developer.home-connect.com/, and then created an Application in the manner specified in the readme.

`homebridge-homeconnect` is now at the stage it's asking me to authorise the ClientID (which is definitely correct) and clicking the link via the settings page takes me to the SingleKey ID page.
There are no questions about just using HomeConnect logins.

This is the page that the authorisation link sends me to:
![image](https://user-images.githubusercontent.com/169223/197360210-ea74e173-d27c-4e20-b6aa-bfe03f033347.png)

That HomeConnect in the top left isn't clickable, it's simply an image that does nothing. There are no ad blockers (or any) extensions loaded in the browser.

This is in the UK, perhaps they've broken the authorization flow here?

**Comment by thoukydides** [comment]
I am now seeing the same.

After creating a SingleKey ID at https://singlekey-id.com/en/sign-up/ I was able to use that to authorise this plugin. I used the same email address as my Home Connect account. All of my Home Connect appliances appeared correctly, without doing anything to link the accounts; presumably using the same email address was sufficient. The Home Connect app still uses the original Home Connect login rather than the new SingleKey ID but still shows all of the appliances.

**Comment by thoukydides** [comment]
There is an interesting note on https://github.com/ekutner/home-connect-hass#faq:
> Home Connect always compares the Singlekey ID to the entry for "Home Connect user account for testing" set in the Developer account in all lowercase, even if capital letters are entered. This means if the Singlekey ID was created with an email with capital letters, the Home Connect backend will give back a invalid_client response. The current workaround is to create a Singlekey ID account with an all lower case email.

**Comment by phyber** [comment]
Thanks for looking into this and confirming the new workflow involving the SingleKey ID.

I think they may also not properly support plus addresses over their multiple systems, I was originally using `my.name+homeconnect@` type email addresses. After simplifying this to just `homeconnect@` across all accounts things seem to be working much better and I was able to successfully authorise my HomeConnect application.
