### ISSUE TITLE
Home Connect API error: fetch failed (Cannot destructure property 'exports' of 'undefined' as it is undefined.)

### ISSUE THREAD

**Issue by DragonIceFreeze** [thoukydides/homebridge-homeconnect#93]
#### Description of Issue

Homebridge cannot start with latest Home Connect version.

#### Plugin Version

homebridge-homeconnect v0.24.5

#### Home Connect Appliance(s)

Siemens Oven HM676G0S6/79

#### Log File

[HomeConnect] Requesting Home Connect authorisation using the Device Flow
[HomeConnect] Home Connect API error: fetch failed (Cannot destructure property 'exports' of 'undefined' as it is undefined.)
[HomeConnect] Retrying client authentication in 60 seconds
TypeError: Cannot read properties of undefined (reading 'timeoutType')
    at _resume (/usr/local/lib/node_modules/homebridge-homeconnect/node_modules/undici/lib/client.js:1167:29)
    at resume (/usr/local/lib/node_modules/homebridge-homeconnect/node_modules/undici/lib/client.js:1131:3)
    at connect (/usr/local/lib/node_modules/homebridge-homeconnect/node_modules/undici/lib/client.js:1116:3)

**Comment by thoukydides** [comment]
This appears to resemble nodejs/undici#1087.

What version of Node.js are you using, and what version of undici is installed?

**Comment by DragonIceFreeze** [comment]
Thanks for the followup.

Node is v16.15.1
Undici is v8.11.0

**Comment by thoukydides** [comment]
I was using Node 16.14.2 and undici 5.5.1 for my own testing. That worked without problems.

I have just updated to Node 16.15.1 and undici 5.6.0. That also works without problems.

**Comment by DragonIceFreeze** [comment]
Ok, thanks a lot. Can you help me test if this is working with undici 5.6.0 on my config? Not sure how I can upgrade the dependency from Homeconnect.

Many thx!

**Comment by thoukydides** [comment]
Presumably you mean from within the [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x). If so, then I don't think there is any way to update individual package dependencies from the web interface.

I have bumped the required undici version to 5.6.0 in the latest (0.24.6) release, so installing that should update the undici version. I doubt whether it will affect this issue though.

**Comment by thoukydides** [comment]
Recent versions of this plugin (0.24.6 and 0.25.0) log some information about some of the software versions being used during start-up. On my production system I get:
```
[HomeConnect] Initializing HomeConnect platform...
[HomeConnect] new HomeConnectPlatform
[HomeConnect] homebridge-homeconnect version 0.25.0
[HomeConnect] Node.js version 16.15.1 (satisfies >=17.3.0 || ^16.14.0)
[HomeConnect] Homebridge version 1.4.1 (satisfies >=1.4.0)
[HomeConnect] Homebridge API version 2.7 (satisfies ^2.7)
[HomeConnect] Homebridge HAP version 0.10.2 (satisfies >=0.9.0)
[HomeConnect] Restored 3 cached accessories
```
Running `npm list` in the directory where the plugin has been installed lists the versions of other libraries that it uses. On my production system I get:
```
homebridge-homeconnect@0.25.0 /home/alex/Documents/Homebridge/Stable/homebridge-homeconnect
├── chalk@4.1.2
├── node-persist@3.1.0
├── pre-commit@1.2.2
├── semver@7.3.7
└── undici@5.7.0
```

**Comment by DragonIceFreeze** [comment]
Well, not sure what happened, but needed to reinstall homebridge + all plugins, and it eventually worked, so it may (must) be linked to my config.
Thanks for the support, I close the ticket.
